CREATE TABLE public.items
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    available     bool NULL,
    description   varchar(255) NULL,
    "name"        varchar(255)                                                                                                             NOT NULL,
    owner_id      varchar(255)                                                                                                             NOT NULL,
    price_per_day float8 NULL,
    stock         int4                                                                                                                     NOT NULL,
    CONSTRAINT items_pkey PRIMARY KEY (id)
);