CREATE TABLE public.rentals
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    approved_by varchar(255) NULL,
    borrower_id varchar(255)                                                                                                             NOT NULL,
    created_at  timestamp(6) NULL,
    end_date    date NULL,
    paid        bool NULL,
    start_date  date NULL,
    status      varchar(255) NULL,
    total_price float8 NULL,
    item_id     int8                                                                                                                     NOT NULL,
    CONSTRAINT rentals_pkey PRIMARY KEY (id),
    CONSTRAINT rentals_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING':: character varying, 'APPROVED':: character varying, 'ONGOING':: character varying, 'COMPLETED':: character varying, 'CANCELLED':: character varying])::text[])
) )
);

ALTER TABLE public.rentals
    ADD CONSTRAINT fk9t4jdsn113em9kyh6wkl81efm FOREIGN KEY (item_id) REFERENCES public.items (id);