CREATE TABLE public.payments
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    amount      float8 NULL,
    paid_at     timestamp(6) NULL,
    payment_ref varchar(255) NULL,
    rental_id   int8                                                                                                                     NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT uk6b9oj6np97hxx2k68lir605ml UNIQUE (rental_id)
);


-- public.payments foreign keys

ALTER TABLE public.payments
    ADD CONSTRAINT fk55tlwg2o3718m5fjunw4omev7 FOREIGN KEY (rental_id) REFERENCES public.rentals (id);